name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert

    - name: Run and Convert Notebooks
      run: |
        jupyter nbconvert --execute --inplace exploratory_data_analysis.ipynb
        jupyter nbconvert --execute --inplace feature_engineering.ipynb
        jupyter nbconvert --execute --inplace feature_selection.ipynb

    - name: Build Docker image
      run: docker build -t ml-model .

    - name: Push Docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag ml-model ghcr.io/${{ github.repository_owner }}/ml-model:latest
        docker push ghcr.io/${{ github.repository_owner }}/ml-model:latest
